package uk.ac.ebi.intact.psi.mi.xmlmaker.file.processing.content;

public enum Databases {
    ABCD("ABCD curated depository of sequenced antibodies", "ABCD"),
    AGR("The Alliance of Genome Resources", "AGR"),
    ALLERGOME("Allergome; a platform for allergen knowledge", "Allergome"),
    ALPHAFOLDDB("AlphaFold Protein Structure Database", "AlphaFoldDB"),
    ANTIBODYPEDIA("Antibodypedia a portal for validated antibodies", "Antibodypedia"),
    ANTIFAM("AntiFam", "AntiFam"),
    ARACHNOSERVER("ArachnoServer: Spider toxin database", "ArachnoServer"),
    ARAPORT("Arabidopsis Information Portal", "Araport"),
    BGEE("Bgee dataBase for Gene Expression Evolution", "Bgee"),
    BINDINGDB("BindingDB database of measured binding affinities", "BindingDB"),
    BIOCYC("BioCyc Collection of Pathway/Genome Databases", "BioCyc"),
    BIOGRID("The Biological General Repository for Interaction Datasets (BioGRID)", "BioGRID"),
    BIOGRID_ORCS("BioGRID ORCS database of CRISPR phenotype screens", "BioGRID-ORCS"),
    BIOMUTA("BioMuta curated single-nucleotide variation and disease association database", "BioMuta"),
    BMRB("Biological Magnetic Resonance Data Bank", "BMRB"),
    BRENDA("BRENDA Comprehensive Enzyme Information System", "BRENDA"),
    CARBONYLDB("CarbonylDB database of protein carbonylation sites", "CarbonylDB"),
    CAZY("Carbohydrate-Active enZymes", "CAZy"),
    CCDS("The Consensus CDS (CCDS) project", "CCDS"),
    CDD("Conserved Domains Database", "CDD"),
    CGD("Candida Genome Database", "CGD"),
    CHEMBL("ChEMBL database of bioactive drug-like small molecules", "ChEMBL"),
    CHITARS("ChiTaRS: a database of human, mouse and fruit fly chimeric transcripts and RNA-sequencing data", "ChiTaRS"),
    CLINGEN("The ClinGen clinical relevance of genes and variants resource", "ClinGen"),
    COLLECTF("CollecTF database of bacterial transcription factor binding sites", "CollecTF"),
    COMPLEXPORTAL("ComplexPortal: manually curated resource of macromolecular complexes", "ComplexPortal"),
    CONOSERVER("ConoServer: Cone snail toxin database", "ConoServer"),
    CORUM("CORUM comprehensive resource of mammalian protein complexes", "CORUM"),
    CPTAC("The CPTAC Assay portal", "CPTAC"),
    CPTC("The CPTC Antibody Portal", "CPTC"),
    CTD("Comparative Toxicogenomics Database", "CTD"),
    DBSNP("Database of single nucleotide polymorphism", "dbSNP"),
    DDBJ("DNA Data Bank of Japan; a nucleotide sequence database", "DDBJ"),
    DEPOD("DEPOD human dephosphorylation database", "DEPOD"),
    DICTYBASE("Dictyostelium discoideum online informatics resource", "dictyBase"),
    DIP("Database of interacting proteins", "DIP"),
    DISGENET("DisGeNET", "DisGeNET"),
    DISPROT("Database of protein disorder", "DisProt"),
    DMDM("Domain mapping of disease mutations (DMDM)", "DMDM"),
    DNASU("The DNASU plasmid repository", "DNASU"),
    DRUGBANK("Drug and drug target database", "DrugBank"),
    DRUGCENTRAL("DrugCentral", "DrugCentral"),
    ECHOBASE("EchoBASE - an integrated post-genomic database for E. coli", "EchoBASE"),
    EGGNOG("evolutionary genealogy of genes: Non-supervised Orthologous Groups", "eggNOG"),
    ELM("The Eukaryotic Linear Motif resource for Functional Sites in Proteins", "ELM"),
    EMBL("EMBL nucleotide sequence database", "EMBL"),
    EMDB("Electron Microscopy Data Bank", "EMDB"),
    ENSEMBL("Ensembl eukaryotic genome annotation project", "Ensembl"),
    ENSEMBLBACTERIA("Ensembl bacterial and archaeal genome annotation project", "EnsemblBacteria"),
    ENSEMBLFUNGI("Ensembl fungal genome annotation project", "EnsemblFungi"),
    ENSEMBLMETAZOA("Ensembl metazoan genome annotation project", "EnsemblMetazoa"),
    ENSEMBLPLANTS("Ensembl plant genome annotation project", "EnsemblPlants"),
    ENSEMBLPROTISTS("Ensembl protists genome annotation project", "EnsemblProtists"),
    ENZYME("Enzyme nomenclature database", "ENZYME"),
    ESTHER("ESTHER database of the Alpha/Beta-hydrolase fold superfamily of proteins", "ESTHER"),
    EUHCVDB("European Hepatitis C Virus Database", "euHCVdb"),
    EVOLUTIONARYTRACE("Relative evolutionary importance of amino acids within a protein sequence", "EvolutionaryTrace"),
    EXPRESSIONATLAS("ExpressionAtlas, Differential and Baseline Expression", "ExpressionAtlas"),
    FLYBASE("Drosophila genome database", "FlyBase"),
    FUNFAM("CATH Functional Families", "FunFam"),
    GENATLAS("GenAtlas: human gene database", "GenAtlas"),
    GENBANK("GenBank nucleotide sequence database", "GenBank"),
    GENCC("GenCC: The Gene Curation Coalition", "GenCC"),
    GENE3D("Gene3D Structural and Functional Annotation of Protein Families", "Gene3D"),
    GENECARDS("GeneCards: human genes, protein and diseases", "GeneCards"),
    GENEID("Database of genes from NCBI RefSeq genomes", "GeneID"),
    GENEREVIEWS("GeneReviews a resource of expert-authored, peer-reviewed disease descriptions.", "GeneReviews"),
    GENETREE("Ensembl GeneTree", "GeneTree"),
    GENEWIKI("The Gene Wiki collection of pages on human genes and proteins", "GeneWiki"),
    GENOMERNai("Database of phenotypes from RNA interference screens in Drosophila and Homo sapiens", "GenomeRNAi"),
    GLYCONNECT("GlyConnect protein glycosylation platform", "GlyConnect"),
    GLYCOSMOS("GlyCosmos Portal integrating glycosciences with life sciences", "GlyCosmos"),
    GLYGEN("GlyGen: Computational and Informatics Resources for Glycoscience", "GlyGen"),
    GO("Gene Ontology", "GO"),
    GPCRDB("Information system for G protein-coupled receptors (GPCRs)", "GPCRDB"),
    GRAMENE("Gramene; a comparative resource for plants", "Gramene"),
    GUIDETOPHARMACOLOGY("IUPHAR/BPS Guide to PHARMACOLOGY", "GuidetoPHARMACOLOGY"),
    HAMAP("HAMAP database of protein families", "HAMAP"),
    HGNC("Human Gene Nomenclature Database", "HGNC"),
    HOGENOM("The HOGENOM Database of Homologous Genes from Fully Sequenced Organisms", "HOGENOM"),
    HPA("Human Protein Atlas", "HPA"),
    HUGE("Human Unidentified Gene-Encoded large proteins database", "HUGE"),
    IDEAL("Intrinsically Disordered proteins with Extensive Annotations and Literature", "IDEAL"),
    IMGT_GENE_DB("The international ImMunoGeneTics information system", "IMGT_GENE-DB"),
    INPARANOID("InParanoid: Ortholog Groups for Protein Domains and Full-Length Proteins", "InParanoid"),
    INTACT("Protein interaction database and analysis system", "IntAct"),
    INTERPRO("Integrated resource of protein families, domains and functional sites", "InterPro"),
    IPTMNET("iPTMnet integrated resource for PTMs in systems biology context", "iPTMnet"),
    JAPONICUSDB("Schizosaccharomyces japonicus model organism database", "JaponicusDB"),
    JPOST("jPOST - Japan Proteome Standard Repository/Database", "jPOST"),
    KEGG("KEGG: Kyoto Encyclopedia of Genes and Genomes", "KEGG"),
    LEGIOLIST("Legionella pneumophila genome database", "LegioList"),
    LEPROMA("Mycobacterium leprae genome database", "Leproma"),
    MAIZEGDB("Maize Genetics and Genomics Database", "MaizeGDB"),
    MALACARDS("MalaCards human disease database", "MalaCards"),
    MANE_SELECT("Matched Annotation from NCBI and EMBL-EBI (MANE) - Phase one", "MANE-Select"),
    MASSIVE("MassIVE - Mass Spectrometry Interactive Virtual Environment", "MassIVE"),
    MEROPS("MEROPS protease database", "MEROPS"),
    METOSITE("MetOSite database of methionine sulfoxide sites", "MetOSite"),
    MGI("Mouse genome database (MGD) from Mouse Genome Informatics (MGI)", "MGI"),
    MIM("Online Mendelian Inheritance in Man (OMIM)", "MIM"),
    MINT("Molecular INTeraction database", "MINT"),
    MOBIDB("MobiDB: a database of protein disorder and mobility annotations", "MobiDB"),
    MODBASE("Database of comparative protein structure models", "ModBase"),
    MOONDB("MoonDB Database of extreme multifunctional and moonlighting proteins", "MoonDB"),
    MOONPROT("MoonProt database of moonlighting proteins", "MoonProt"),
    NCBIFAM("NCBIfam", "NCBIfam"),
    NEXTPROT("neXtProt; the human protein knowledge platform", "neXtProt"),
    NIAGADS("NIAGADS Genomics Database", "NIAGADS"),
    OGP("USC-OGP 2-DE database", "OGP"),
    OMA("Identification of Orthologs from Complete Genome Data", "OMA"),
    OPENTARGETS("Open Targets", "OpenTargets"),
    ORPHANET("Orphanet; a database dedicated to information on rare diseases and orphan drugs", "Orphanet"),
    ORTHODB("Database of Orthologous Groups", "OrthoDB"),
    PANTHER("The PANTHER Classification System", "PANTHER"),
    PATHWAYCOMMONS("Pathway Commons web resource for biological pathway data", "PathwayCommons"),
    PATRIC("Pathosystems Resource Integration Center (PATRIC)", "PATRIC"),
    PAXDB("PaxDb, a database of protein abundance averages across all three domains of life", "PaxDb"),
    PCDDB("The Protein Circular Dichroism Data Bank", "PCDDB"),
    PDB("Protein Data Bank Europe", "PDB"),
    PDBE_KB("Protein Data Bank in Europe - Knowledge Base", "PDBe-KB"),
    PDBJ("Protein Data Bank Japan", "PDBj"),
    PDBSUM("PDBsum; at-a-glance overview of macromolecular structures", "PDBsum"),
    PEPTIDEATLAS("PeptideAtlas", "PeptideAtlas"),
    PEROXIBASE("PeroxiBase, a peroxidase database", "PeroxiBase"),
    PFAM("Pfam protein domain database", "Pfam"),
    PHARMGKB("The Pharmacogenetics and Pharmacogenomics Knowledge Base", "PharmGKB"),
    PHAROS("Pharos NIH Druggable Genome Knowledgebase", "Pharos"),
    PHI_BASE("Pathogen-Host Interaction database", "PHI-base"),
    PHOSPHOSITEPLUS("Comprehensive resource for the study of protein post-translational modifications (PTMs) in human, mouse and rat.", "PhosphoSitePlus"),
    PHYLOMEDB("Database for complete collections of gene phylogenies", "PhylomeDB"),
    PIR("Protein sequence database of the Protein Information Resource", "PIR"),
    PIRSF("PIRSF; a whole-protein classification database", "PIRSF"),
    PLANTREACTOME("Reactome - a knowledgebase of biological pathways and processes for plant species", "PlantReactome"),
    POMBASE("Schizosaccharomyces pombe database", "PomBase"),
    PRIDE("PRoteomics IDEntifications database", "PRIDE"),
    PRINTS("Protein Motif fingerprint database; a protein domain database", "PRINTS"),
    PRO("Protein Ontology", "PRO"),
    PROMEX("Protein Mass spectra EXtraction", "ProMEX"),
    PROSITE("PROSITE; a protein domain and family database", "PROSITE"),
    PROTEOMES("Proteomes", "Proteomes"),
    PROTEOMICSDB("ProteomicsDB: a multi-organism proteome resource", "ProteomicsDB"),
    PSEUDOCAP("Pseudomonas genome database", "PseudoCAP"),
    PUMBA("Pumba database of electrophoretic reference migration patterns", "Pumba"),
    RCSB_PDB("Protein Data Bank RCSB", "RCSB-PDB"),
    REACTOME("Reactome - a knowledgebase of biological pathways and processes", "Reactome"),
    REBASE("Restriction enzymes and methylases database", "REBASE"),
    REFSEQ("NCBI Reference Sequences", "RefSeq"),
    REPRODUCTION_2DPAGE("REPRODUCTION-2DPAGE", "REPRODUCTION-2DPAGE"),
    RGD("Rat Genome Database", "RGD"),
    RNACT("RNAct, Protein-RNA interaction predictions for model organisms.", "RNAct"),
    ROUGE("Rodent Unidentified Gene-Encoded large proteins database", "Rouge"),
    SABIO_RK("SABIO-RK: Biochemical Reaction Kinetics Database", "SABIO-RK"),
    SASBDB("Small Angle Scattering Biological Data Bank", "SASBDB"),
    SFLD("Structure-Function Linkage Database", "SFLD"),
    SGD("Saccharomyces Genome Database", "SGD"),
    SIGNALINK("SignaLink: a signaling pathway resource with multi-layered regulatory networks", "SignaLink"),
    SIGNOR("SIGNOR Signaling Network Open Resource", "SIGNOR"),
    SMART("Simple Modular Architecture Research Tool; a protein domain database", "SMART"),
    SMR("SWISS-MODEL Repository - a database of annotated 3D protein structure models", "SMR"),
    SOURCE("The Stanford Online Universal Resource for Clones and ESTs", "SOURCE"),
    STRING("STRING: functional protein association networks", "STRING"),
    SUPFAM("Superfamily database of structural and functional annotation", "SUPFAM"),
    SWISS_MODEL_WORKSPACE("SWISS-MODEL Interactive Workspace", "SWISS-MODEL-Workspace"),
    SWISSLIPIDS("SwissLipids knowledge resource for lipid biology", "SwissLipids"),
    SWISSPALM("SwissPalm database of S-palmitoylation events", "SwissPalm"),
    TAIR("The Arabidopsis Information Resource", "TAIR"),
    TCDB("Transport Classification Database", "TCDB"),
    TOPDOWNPROTEOMICS("Consortium for Top Down Proteomics", "TopDownProteomics"),
    TREEFAM("TreeFam database of animal gene trees", "TreeFam"),
    TUBERCULIST("Mycobacterium tuberculosis strain H37Rv genome database", "TubercuList"),
    UCSC("UCSC genome browser", "UCSC"),
    UNILECTIN("UniLectin database of carbohydrate-binding proteins", "UniLectin"),
    UNIPATHWAY("UniPathway: a resource for the exploration and annotation of metabolic pathways", "UniPathway"),
    VEUPATHDB("Eukaryotic Pathogen, Vector and Host Database Resources", "VEuPathDB"),
    VGNC("Vertebrate Gene Nomenclature Database", "VGNC"),
    WBPARASITE("WormBase ParaSite", "WBParaSite"),
    WORMBASE("WormBase", "WormBase"),
    XENBASE("Xenopus laevis and tropicalis biology and genomics resource", "Xenbase"),
    ZFIN("Zebrafish Information Network genome database", "ZFIN");

    public final String name;
    public final String abbrev;

    Databases(String name, String abbrev) {
        this.name = name;
        this.abbrev = abbrev;
    }

}