package uk.ac.ebi.intact.psi.mi.xmlmaker.file.processing.content;

public enum InteractionType {
    ACETYLATION("Acetylation", "EBI-49847"),
    ADP_DERIBOSYLATION("ADP Deribosylation", "EBI-26356759"),
    ADP_RIBOSYLATION("ADP Ribosylation", "EBI-608837"),
    AMIDATION("Amidation", "EBI-49850"),
    AMINOACYLATION("Aminoacylation", "EBI-5528230"),
    AMPYLATION("Ampylation", "EBI-5528218"),
    APHENOTYPIC_NEUTRAL_MULTIGENIC_PHENOTYPE_RESULT("Aphenotypic Neutral Multigenic Phenotype Result", "EBI-28957105"),
    APHENOTYPIC_PHENOTYPE_RESULT("Aphenotypic Phenotype Result", "EBI-28956978"),
    ASSOCIATION("Association", "EBI-1813191"),
    ASYNTHETIC("Asynthetic", "EBI-1218352"),
    ATPASE_REACTION("ATPase Reaction", "EBI-1372271"),
    CARBOXYLATION("Carboxylation", "EBI-5528238"),
    CISPHENOTYPIC_CO_SUPPRESSING_GENETIC_INTERACTION("Cisphenotypic Co-Suppressing Genetic Interaction", "EBI-28957102"),
    CISPHENOTYPIC_GENETIC_SUPPRESSION("Cisphenotypic Genetic Suppression", "EBI-6862145"),
    CISPHENOTYPIC_GENETIC_SUPPRESSION_COMPLETE("Cisphenotypic Genetic Suppression (Complete)", "EBI-28957108"),
    CISPHENOTYPIC_GENETIC_SUPPRESSION_PARTIAL("Cisphenotypic Genetic Suppression (Partial)", "EBI-6862141"),
    CISPHENOTYPIC_INTER_SUPPRESSING_GENETIC_INTERACTION("Cisphenotypic Inter-Suppressing Genetic Interaction", "EBI-6862161"),
    CISPHENOTYPIC_PHENOTYPE_RESULT("Cisphenotypic Phenotype Result", "EBI-28957021"),
    CLEAVAGE("Cleavage", "EBI-49853"),
    COLOCALIZATION("Colocalization", "EBI-608832"),
    CONVERGING_GENETIC_EPISTASIS("Converging Genetic Epistasis", "EBI-6862109"),
    CONVERGING_GENETIC_INTERACTION("Converging Genetic Interaction", "EBI-1813172"),
    COVALENT_BINDING("Covalent Binding", "EBI-49856"),
    DE_ADP_RIBOSYLATION_REACTION("De-ADP-Ribosylation Reaction", "EBI-6862104"),
    DEACETYLATION("Deacetylation", "EBI-49862"),
    DEAMIDATION("Deamidation", "EBI-16212823"),
    DEAMINATION("Deamination", "EBI-5528210"),
    DECARBOXYLATION("Decarboxylation", "EBI-5528234"),
    DEFARNESYLATION("Defarnesylation", "EBI-49865"),
    DEFORMYLATION("Deformylation", "EBI-49868"),
    DEGLYCOSYLATION("Deglycosylation", "EBI-608838"),
    DELETERIOUS_MULTIGENIC_PHENOTYPE_RESULT("Deleterious Multigenic Phenotype Result", "EBI-28957040"),
    DEMETHYLATION("Demethylation", "EBI-1372248"),
    DENEDDYLATION("Deneddylation", "EBI-705110"),
    DEPALMITOYLATION("Depalmitoylation", "EBI-49877"),
    DEPHOSPHORYLATION("Dephosphorylation", "EBI-49880"),
    DESUMOYLATION("Desumoylation", "EBI-705151"),
    DEUBIQUITINATION("Deubiquitination", "EBI-49883"),
    DIPHITHAMIDATION("Diphthamidation", "EBI-5528252"),
    DIRECT_INTERACTION("Direct Interaction", "EBI-608833"),
    DISULFIDE_BOND("Disulfide Bond", "EBI-608834"),
    DIVERGING_GENETIC_INTERACTION("Diverging Genetic Interaction", "EBI-1812885"),
    DNA_CLEAVAGE("DNA Cleavage", "EBI-705175"),
    DNA_ELONGATION("DNA Elongation", "EBI-968003"),
    DOSAGE_GROWTH_DEFECT("Dosage Growth Defect (sensu BioGRID)", "EBI-28957087"),
    DOSAGE_LETHALITY("Dosage Lethality (sensu BioGRID)", "EBI-28957084"),
    DOSAGE_RESCUE("Dosage Rescue (sensu BioGRID)", "EBI-28957066"),
    ENZYMATIC_REACTION("Enzymatic Reaction", "EBI-608836"),
    EPISTATIC("Epistatic", "EBI-1218387"),
    FARNESYLATION("Farnesylation", "EBI-49889"),
    FORMYLATION("Formylation", "EBI-49892"),
    FUNCTIONAL_ASSOCIATION("Functional Association", "EBI-21134183"),
    GENETIC_ENHANCEMENT("Genetic Enhancement", "EBI-28957027"),
    GENETIC_ENHANCEMENT_SENSU_UNEXPECTED("Genetic Enhancement (sensu Unexpected)", "EBI-6862121"),
    GENETIC_OVER_SUPPRESSION("Genetic Over-Suppression", "EBI-28956998"),
    GENETIC_SUPPRESSION_COMPLETE("Genetic Suppression (Complete)", "EBI-6862201"),
    GENETIC_SUPPRESSION_PARTIAL("Genetic Suppression (Partial)", "EBI-6862197"),
    GERANYLGERANYLATION("Geranylgeranylation", "EBI-49898"),
    GLYCOSYLATION("Glycosylation", "EBI-608839"),
    GTPASE_REACTION("GTPase Reaction", "EBI-1372266"),
    GUANINE_NUCLEOTIDE_EXCHANGE_FACTOR_REACTION("Guanine Nucleotide Exchange Factor Reaction", "EBI-21134187"),
    HYDROXYLATION("Hydroxylation", "EBI-49901"),
    INTERACTION_TYPE("Interaction Type", "EBI-636628"),
    ISOMERASE_REACTION("Isomerase Reaction", "EBI-6353853"),
    ISOPHENOTYPIC_PHENOTYPE_RESULT("Isophenotypic Phenotype Result", "EBI-28957024"),
    LIPID_ADDITION("Lipid Addition", "EBI-49904"),
    LIPID_CLEAVAGE("Lipid Cleavage", "EBI-9873202"),
    LIPID_CLEAVAGE_2("Lipid Cleavage-2", "EBI-49907"),
    MAXIMAL_GENETIC_EPISTASIS("Maximal Genetic Epistasis", "EBI-6862113"),
    METHYLATION("Methylation", "EBI-49910"),
    METHYLMALONYL_COA_ISOMERASE_REACTION("Methylmalonyl-CoA Isomerase Reaction", "EBI-6353857"),
    MINIMAL_GENETIC_EPISTASIS("Minimal Genetic Epistasis", "EBI-6862137"),
    MOLECULAR_ASSOCIATION("Molecular Association", "EBI-16372472"),
    MONOPHENOTYPIC_GENETIC_ENHANCEMENT("Monophenotypic Genetic Enhancement", "EBI-6862149"),
    MONOPHENOTYPIC_GENETIC_OVER_SUPPRESSION("Monophenotypic Genetic Over-Suppression", "EBI-6862189"),
    MONOPHENOTYPIC_GENETIC_SUPPRESSION("Monophenotypic Genetic Suppression", "EBI-6862185"),
    MONOPHENOTYPIC_GENETIC_SUPPRESSION_COMPLETE("Monophenotypic Genetic Suppression (Complete)", "EBI-6862181"),
    MONOPHENOTYPIC_GENETIC_SUPPRESSION_PARTIAL("Monophenotypic Genetic Suppression (Partial)", "EBI-6862193"),
    MONOPHENOTYPIC_NEUTRAL_MULTIGENIC_PHENOTYPE_RESULT("Monophenotypic Neutral Multigenic Phenotype Result", "EBI-28957081"),
    MONOPHENOTYPIC_PHENOTYPE_RESULT("Monophenotypic Phenotype Result", "EBI-28956989"),
    MRNA_CLEAVAGE("mRNA Cleavage", "EBI-705182"),
    MULTIGENIC_PHENOTYPE_RESULT("Multigenic Phenotype Result", "EBI-28956995"),
    MUTUAL_GENETIC_ENHANCEMENT("Mutual Genetic Enhancement", "EBI-28957037"),
    MUTUAL_GENETIC_ENHANCEMENT_EXPECTED("Mutual Genetic Enhancement (Expected)", "EBI-28957099"),
    MUTUAL_GENETIC_ENHANCEMENT_SENSU_UNEXPECTED("Mutual Genetic Enhancement (sensu Unexpected)", "EBI-6862153"),
    MUTUAL_GENETIC_OVER_SUPPRESSION("Mutual Genetic Over-Suppression", "EBI-6862173"),
    MUTUAL_GENETIC_SUPPRESSION("Mutual Genetic Suppression", "EBI-28957034"),
    MUTUAL_GENETIC_SUPPRESSION_COMPLETE("Mutual Genetic Suppression (Complete)", "EBI-6862157"),
    MYRISTOYLATION("Myristoylation", "EBI-49913"),
    NCL_ACID_CLEAVAGE("Nucleic Acid Cleavage", "EBI-1812605"),
    NEDDYLATION("Neddylation", "EBI-705170"),
    NEGATIVE_GENETIC_INTERACTION("Negative Genetic Interaction", "EBI-28957052"),
    NEGATIVE_GENETIC_INTERACTION_SENSU_BIOGRID("Negative Genetic Interaction (sensu BioGRID)", "EBI-28957069"),
    NEUTRAL_EPISTASIS("Neutral Epistasis", "EBI-6862129"),
    NEUTRAL_GENT_INT("Neutral Genetic Interaction", "EBI-1813206"),
    NEUTRAL_MULTIGENIC_PHENOTYPE_RESULT("Neutral Multigenic Phenotype Result", "EBI-1813028"),
    OPPOSING_GENETIC_EPISTASIS("Opposing Genetic Epistasis", "EBI-6862125"),
    P_PANTETHEINYLATION("P-Pantetheinylation", "EBI-5528226"),
    PALMITOYLATION("Palmitoylation", "EBI-49919"),
    PHENOTYPE_BIAS("Phenotype Bias", "EBI-6862205"),
    PHENOTYPIC_ENHANCEMENT_SENSU_BIOGRID("Phenotypic Enhancement (sensu BioGRID)", "EBI-28957075"),
    PHENOTYPIC_SUPPRESSION_SENSU_BIOGRID("Phenotypic Suppression (sensu BioGRID)", "EBI-28957072"),
    PHOSPHOLIPASE_REACTION("Phospholipase Reaction", "EBI-5528222"),
    PHOSPHORYLATION("Phosphorylation", "EBI-49922"),
    PHOSPHOTRANSFER("Phosphotransfer", "EBI-1218345"),
    PHYSICAL_ASSOCIATION("Physical Association", "EBI-1813147"),
    POSITIVE_GENETIC_INTERACTION_SENSU_BIOGRID("Positive Genetic Interaction (sensu BioGRID)", "EBI-28957043"),
    POSITIVE_GENT_INT("Positive Genetic Interaction", "EBI-28957061"),
    PREDICTED("Predicted", "EBI-5528214"),
    PROLINE_ISOMERIZATION_REACTION("Proline Isomerization Reaction", "EBI-6353865"),
    PROTEIN_CLEAVAGE("Protein Cleavage", "EBI-705088"),
    PROXIMITY("Proximity", "EBI-26564119"),
    PUTATIVE_SELF_INTERACTION("Putative Self Interaction", "EBI-5528247"),
    QUALITATIVE_GENETIC_EPISTASIS("Qualitative Genetic Epistasis", "EBI-6862133"),
    QUANTITATIVE_GENETIC_EPISTASIS("Quantitative Genetic Epistasis", "EBI-6862117"),
    REDOX_REACTION("Redox Reaction", "EBI-2474829"),
    RNA_CLEAVAGE("RNA Cleavage", "EBI-1813280"),
    RNA_ELONGATION("RNA Elongation", "EBI-5528206"),
    S_NITROSYLATION("S-Nitrosylation", "EBI-16372485"),
    SELF_INTERACTION("Self Interaction", "EBI-5528242"),
    STRAND_ELONGATION("Strand Elongation", "EBI-5527531"),
    SULFURTRANSFER("Sulfurtransfer", "EBI-9095115"),
    SUMOYLATION("Sumoylation", "EBI-705098"),
    SUPPRESSION("Suppression", "EBI-705214"),
    SURPASSING_GENETIC_INTERACTION("Surpassing Genetic Interaction", "EBI-6862169"),
    SYNTHETIC_GENETIC_INTERACTION("Synthetic Genetic Interaction", "EBI-1218366"),
    SYNTHETIC_GROWTH_DEFECT("Synthetic Growth Defect (sensu BioGRID)", "EBI-28957078"),
    SYNTHETIC_HAPLOINSUFFICIENCY("Synthetic Haploinsufficiency (sensu BioGRID)", "EBI-28957046"),
    SYNTHETIC_LETHALITY("Synthetic Lethality (sensu BioGRID)", "EBI-28957049"),
    SYNTHETIC_RESCUE("Synthetic Rescue (sensu BioGRID)", "EBI-28957058"),
    TRANSGUTAMINATION("Transglutamination", "EBI-608835"),
    TRANSPHENOTYPIC_ENHANCING_GENETIC_INTERACTION("Transphenotypic Enhancing Genetic Interaction", "EBI-6862177"),
    TRANSPHENOTYPIC_GENETIC_SUPPRESSION("Transphenotypic Genetic Suppression", "EBI-28957093"),
    TRANSPHENOTYPIC_GENETIC_SUPPRESSION_COMPLETE("Transphenotypic Genetic Suppression (Complete)", "EBI-28957096"),
    TRANSPHENOTYPIC_GENETIC_SUPPRESSION_EXPECTED("Transphenotypic Genetic Suppression (Expected)", "EBI-28957090"),
    TRANSPHENOTYPIC_PHENOTYPE_RESULT("Transphenotypic Phenotype Result", "EBI-28956992"),
    TRIPHOSPHATASE_REACT("Triphosphatase Reaction", "EBI-1372255"),
    TYROSINATION("Tyrosination", "EBI-16372488"),
    TYROSINYLATION("Tyrosinylation", "EBI-16372491"),
    UBIQUITINATION("Ubiquitination", "EBI-49931"),
    URIDYLATION("Uridylation", "EBI-6353861");


    public final String name;
    public final String ebiId;

    InteractionType(String name, String ebiId){
        this.name = name;
        this.ebiId = ebiId;
    }
}
