package uk.ac.ebi.intact.psi.mi.xmlmaker.file.processing.content;

public enum ParticipantDetectionMethod {
    ANTI_TAG_IMMUNOST("Anti-Tag Immunostaining", "EBI-967836"),
    ANTI_TAG_WESTERN("Anti-Tag Western Blot", "EBI-967832"),
    ANTI_TAG_IMMUNOCYTOCHEMISTRY("Anti-Tag Immunocytochemistry", "EBI-6349980"),
    ANTI_TAG_IMMUNOHISTOCHEMISTRY("Anti-Tag Immunohistochemistry", "EBI-6350007"),
    ANTIBODY_DETECTION("Antibody Detection", "EBI-608791"),
    AUTORADIOGRAPHY("Autoradiography", "EBI-1372407"),
    DE_NOVO_PROTEIN_SEQUENCE("De Novo Protein Sequence", "EBI-945"),
    EDMAN_DEGRADATION("Edman Degradation", "EBI-949"),
    ELISA("ELISA", "EBI-608792"),
    EXPERIMENTAL_PARTICIPATION("Experimental Participation", "EBI-933978"),
    FINGERPRINTING("Fingerprinting", "EBI-70"),
    FULL_DNA_SEQUENCE("Full DNA Sequence", "EBI-952"),
    FULL_IDENTIFICATION_BY_RNA_SEQUENCING("Full Identification by RNA Sequencing", "EBI-6349992"),
    ILLUMINA_SEQUENCING("Illumina Sequencing", "EBI-21134192"),
    IMMUNOCYTOCHEMISTRY("Immunocytochemistry", "EBI-6349984"),
    IMMUNOHISTOCHEMISTRY("Immunohistochemistry", "EBI-6349998"),
    IMMUNOSTAINING("Immunostaining", "EBI-608793"),
    INFERENCE("Inference", "EBI-933972"),
    INFERENCE_BY_QUANTITATIVE_CO_PURIFICATION("Inference by Quantitative Co-Purification", "EBI-11763040"),
    INFERRED_BY_AUTHOR("Inferred by Author", "EBI-933992"),
    INFERRED_BY_CURATOR("Inferred by Curator", "EBI-933982"),
    MONOCLONAL_IMMUNOST("Monoclonal Immunostaining", "EBI-967840"),
    MONOCLONAL_WESTERN("Monoclonal Western Blot", "EBI-955"),
    MS_PARTICIPANT("MS Participant", "EBI-608794"),
    MUDPIT("MudPIT", "EBI-933988"),
    NGS_SEQUENCING("NGS Sequencing", "EBI-21134012"),
    NORTHERN_BLOT("Northern Blot", "EBI-1812930"),
    NUCLEOTIDE_SEQUENCE("Nucleotide Sequence", "EBI-958"),
    PAIRED_END_TAGS("Paired-End Tags", "EBI-6349976"),
    PARTIAL_DNA_SEQUENCE("Partial DNA Sequence", "EBI-6349959"),
    PARTIAL_DNA_SEQUENCE_HYBRID("Partial DNA Sequence Hybrid", "EBI-961"),
    PARTIAL_ID_PROT_SEQ("Partial Protein Sequence Identification", "EBI-608795"),
    PARTIAL_NUCLEOTIDE_SEQUENCE("Partial Nucleotide Sequence", "EBI-6349963"),
    PARTIAL_RNA_SEQUENCE("Partial RNA Sequence", "EBI-6350015"),
    PEPTIDE_SYNTHESIS("Peptide Synthesis", "EBI-75"),
    PLA("PLA", "EBI-1218619"),
    POLYCLONAL_IMMUNOST("Polyclonal Immunostaining", "EBI-967828"),
    POLYCLONAL_WESTERN("Polyclonal Western Blot", "EBI-964"),
    PREDETERMINED("Predetermined", "EBI-1465"),
    PREDETERMINED_FEATURE("Predetermined Feature", "EBI-1218644"),
    PRIMER_EXTENSION_ASSAY("Primer Extension Assay", "EBI-10960468"),
    PRIMER_SPECIFIC_PCR("Primer-Specific PCR", "EBI-967"),
    PROTEIN_A_VISUALISATION("Protein A Visualisation", "EBI-5528044"),
    PROTEIN_SEQUENCE("Protein Sequence", "EBI-78"),
    Q_PCR("Q-PCR", "EBI-6350023"),
    QRT_PCR("qRT-PCR", "EBI-6350019"),
    RADIOIMMUNOASSAY("Radioimmunoassay", "EBI-6350002"),
    RT_PCR("RT-PCR", "EBI-6350011"),
    SEQUENCE_TAG("Sequence Tag", "EBI-81"),
    SOCIOAFFINITY_INFERENCE("Socioaffinity Inference", "EBI-11763032"),
    SOUTHERN_BLOT("Southern Blot", "EBI-970"),
    STRUCTURE_DETERMINATION("Structure Determination", "EBI-20597534"),
    TAG_ALK_PHOSPHATASE_ACTIVITY("Tag Alk Phosphatase Activity", "EBI-9095106"),
    TAG_DNA_METHYLTRANSFERASE("Tag DNA Methyltransferase", "EBI-6349988"),
    TAG_ENZYME_ASSAY("Tag Enzyme Assay", "EBI-5528052"),
    TAG_FLUORESCENCE("Tag Fluorescence", "EBI-1372411"),
    TAG_LUCIFERASE("Tag Luciferase", "EBI-6145061"),
    TAG_PEROX_ACTIVITY("Tag Peroxidase Activity", "EBI-5528048"),
    TAG_VISUALISATION("Tag Visualisation", "EBI-1372415"),
    TAG_VISUALISATION_MUTATED_DNA_ADENINE_METHYLTRANSFERASE("Tag Visualisation by Mutated DNA Adenine Methyltransferase", "EBI-6349995"),
    WEIGHT_AUTORADIOGRAPHY("Weight by Autoradiography", "EBI-1218638"),
    WEIGHT_BY_BROMIDE("Weight by Bromide", "EBI-1218625"),
    WEIGHT_BY_COMASSIE("Weight by Coomassie", "EBI-1218596"),
    WEIGHT_BY_HOECHST("Weight by Hoechst", "EBI-1218609"),
    WEIGHT_BY_STAINING("Weight by Staining", "EBI-1218615"),
    WEIGHT_BY_SYBR("Weight by SYBR", "EBI-1218604"),
    WEIGHT_IDENTIFICATION("Weight Identification", "EBI-1218632"),
    WEIGHT_SILVER_STAIN("Weight by Silver Stain", "EBI-1218600"),
    WESTERN_BLOT("Western Blot", "EBI-973");


    public final String name;
    public final String ebiId;

    ParticipantDetectionMethod(String name, String ebiId){
        this.name = name;
        this.ebiId = ebiId;
    }
}
